apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      containers:
      - name: freeswitch
        image: safarov/freeswitch:latest
        ports:
        - containerPort: 5060
          protocol: UDP
        - containerPort: 5066
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        livenessProbe:
          exec:
            command: ["fs_cli", "-x", "status"]
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: freeswitch-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 5060
    targetPort: 5060
    protocol: UDP
    name: sip
  - port: 5066
    targetPort: 5066
    protocol: TCP
    name: wss
  selector:
    app: freeswitch