apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusionpbx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusionpbx
  template:
    metadata:
      labels:
        app: fusionpbx
    spec:
      containers:
      - name: fusionpbx
        image: custom/fusionpbx:latest
        ports:
        - containerPort: 80
        env:
        - name: FS_HOST
          value: "freeswitch-lb"
        - name: DB_HOST
          value: "localhost"
        - name: DB_NAME
          value: "fusionpbx"
        - name: DB_USER
          value: "fusionpbx"
        - name: DB_PASS
          value: "fusionpbx"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fusionpbx
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: fusionpbx